site:
  title: Документация
  # the 404 page and sitemap files only get generated when the url property is set
  url: https://docs.example.ru/
  start_page: main::index.adoc
asciidoc:
  attributes:
    experimental: ''
    #TODO kroki-server-url: http://localhost:8080
    kroki-fetch-diagram: true
    icons: font
    name: АС Название
    url: https://example.ru/
    email: mailto:help@example.ru?subject=Тема
  extensions:
  - ./lib/lorem-block.js
  - asciidoctor-chart
  - asciidoctor-kroki
content:
  edit_url: 'https://github.com/Ingeniator/antora-documentation/edit/{path}'
  sources:
  - url: .
    branches: HEAD
    start_path: main
  - url: .
    branches: HEAD
    start_path: user-guide
  - url: .
    branches: HEAD
    start_path: developer-guide
  - url: .
    branches: HEAD
    start_path: administrator-guide
  - url: .
    branches: HEAD
    start_path: writer-guide
ui:
  bundle:
    #url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    url: ./docs-ui/ui-bundle.zip
    snapshot: true
  supplemental_files: ./docs-ui/supplemental-ui
  #supplemental_files: /usr/local/lib/node_modules/antora-lunr/supplemental_ui
