= My Antora Demo Site and Playbook Project

== Generate the Demo Site

To build run 

``
docker build --build-arg node="node:latest" --build-arg nginx="nginx:stable" -t ant -f devops/docker/Dockerfile .; docker run -p 80:8080 ant
``

To check xrefs before build:

``
$ npm install -g gitlab:antora/xref-validator
$ NODE_PATH="$(npm -g root)" antora --generator @antora/xref-validator antora-playbook.yml
``

To make gif from mov

``
ffmpeg -ss 0 -t 5 -i test.mov -vf "fps=10,split[s0][s1];[s0]palettegen[p];[s1][p]paletteuse" -loop 0 output.gif
``

== Inspired by 

https://fedoramagazine.org/using-antora-for-your-open-source-documentation/
https://docs.antora.org/antora/2.3/
https://owncloud.com/news/owncloud-docs-migrating-antora-pt-1-2/
https://github.com/couchbase/docs-site
https://docs.couchbase.com/home/index.html
https://github.com/couchbase/docs-ui

== TODO

* add extensions https://docs.antora.org/antora/2.3/playbook/asciidoc-extensions/ 
** tabs
** swagger
** https://docs.asciidoctor.org/asciidoctor.js/latest/extend/extensions/ecosystem/
** run local https://kroki.io
** more extentions https://gitlab.com/djencks/simple-examples/-/tree/main
** https://gitlab.com/djencks/asciidoctor-openblock
* write extension https://docs.asciidoctor.org/asciidoctor.js/latest/extend/extensions/ for https://gebish.org/manual/current/#introduction
* add lunr ru search https://gitlab.com/antora/antora-lunr-extension
** https://github.com/Mogztter/antora-lunr/blob/main/lib/generate-index.js
** https://lunrjs.com/guides/language_support.html
* my screenshots 
** https://github.com/Mogztter/asciidoctor-kroki/blob/master/dist/browser/asciidoctor-kroki.js
** https://github.com/asciidoctor/asciidoctorj-screenshot/blob/master/src/main/groovy/org/asciidoctor/extension/ScreenshotMacroBlock.groovy
** https://github.com/asciidoctor/asciidoctorj-screenshot
** https://asciidoctor.github.io/asciidoctor.js/2.2.5/#inlinecreate

https://github.com/puppeteer/puppeteer
https://stackoverflow.com/questions/23729585/generate-animated-gif-with-gm-in-node-js
https://www.npmjs.com/package/make-a-gif
https://dev.to/rajnavadiya786/how-to-capture-website-screenshots-using-node-js-and-puppeteer-35i9
https://hackernoon.com/how-to-take-screenshots-in-the-browser-using-javascript-l92k3xq7
== Copyright and License

Copyright (C) 2021 Ingeniator

Use of this software is granted under the terms of the https://www.mozilla.org/en-US/MPL/2.0/[Mozilla Public License Version 2.0] (MPL-2.0).
See link:LICENSE[] to find the full license text.

